config/routes.rb
Userblog::Application.routes.draw do

   
  devise_for :users
  get "/about", to: "pages#about"
	resources :post do 
		resources :comments
	end
	root "post#index"  
	 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, presence: true, length:{minimum: 5}
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy 
	validates :title, presence: true, length:{minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def new
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build
	end	

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		if @comment.save
			redirect_to @post
	    	else
			render 'new'
	    	end	
	end
	
	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		if @comment.update(post_params)
		   redirect_to @post
		else
		   render 'edit'
	    	end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private
	  	def post_params
			params.require(:comment).permit(:name, :body)
	  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]	
	
	def index
		@posts=Post.all.order('created_at DESC')
	end
	
	def new
		@post=Post.new 
	end
	
	def create
	    @post = Post.new(post_params)
	    if @post.save
		redirect_to @post
	    else
		render 'new'
	    end
	end

	def show
		@post=Post.find(params[:id])
	end
	
	def edit
		@post=Post.find(params[:id])
	end
	
	def update
		@post=Post.find(params[:id])
	
		if @post.update(post_params)
		   redirect_to @post
		else
		   render 'edit'
	    	end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
	
		redirect_to root_path
	end
	
	private
	  def post_params
		params.require(:post).permit(:title, :body)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
<div class="comment clearfix">
	<div class="comment_content">
		
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
		
	</div>
<%if user_signed_in?%>
	 	
	
	<p class="button"><%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></p> 		<p class="button"><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></p>
<%end%>
</div>
<%end%>

app/views/comments/_form.html.erb
<%= form_for([@comment.post, @comment]) do |f| %>
			<% if @comment.errors.any?%>
			<div>	
			<h2><%=pluralize(@comment.errors.count,"error")%> preveted this post form saving</h2>
			<ul>
			<%@comment.errors.full_messages.each do |msg|%>
				<li><%=msg%></li>
			<%end%>
			</ul>
			</div>
			<%end%>
		
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<br>
<%= f.label :body %><br>
<%= f.text_area :body %><br>
<br>
<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Comment</h1>
	<%=render 'form'%>
</div>

 
 

app/views/comments/new.html.erb
<div id="page_wrapper">
<h1>New Comment</h1>
<%= render 'form'%> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", "http://fonts.googleapis.com/css?family=Raleway:400,700" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'oko.jpg' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="sidebar">
	<div id="logo">
		<%= link_to root_path do %>
		<%= image_tag "oko_1.jpg"%> 
		<%end%>
	</div>
		<ul>
			<li class="category">Website</li>
			<li><%=link_to "Blog", root_path%></li>
			<li><%=link_to "About", about_path%></li>
		</ul>

		<ul>
			<li class="cathegory">Social</li>
			<li><a href="https://twitter.com/SAKI_KNIN">Twitter</li>
			<li><a href="https://github.com/sakiKnin">GitHub</li>
			<li><a href="https://www.facebook.com/SaKiKnin">FaceBook</li>
			<li><a href="mailto:boris.saric@gmail.com">Email</li>
		</ul>
		<% if !user_signed_in?%>
			<p class="sign_in"><%= link_to('Login', new_user_session_path) %></p>
		<%end%>

</div>
<div id="main_content">
	<div id="header">
		<% if current_page?(root_path)%>
			 <%=link_to "All posts", root_path%> 
		<% elsif current_page?(about_path)%>
			<%=link_to "About", about_path%>
		<%else%>
			<%=link_to "Back to All Posts", root_path%>
		<%end%>
		<% if user_signed_in? %>
		 	<div class="buttons">
			<p class="button"><%= link_to "New Post", new_post_path %></p>
			<p class="button"><%= link_to('logout', destroy_user_session_path, :method => :delete) %></p>
		 	</div>
		<%end%>
	</div>
		<% flash.each do |name, msg|%>
		<%=content_tag(:div, msg, class:"alert")%>
		<%end%>
		<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
<div id="profile_image">
<%= image_tag "data-image.jpeg" %>
</div>
<div id="content">
<h1>Hey, I'm SAKI_KNIN</h1>
<p>Welcome!!</p>
<p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter <a href="http://twitter.com/SAKI_KNIN">@SAKI_KNIN</a></p>
</div>
</div>

app/views/post/_form_create.html.erb
<%= form_for @post, :url=>{:action=>:create} do |f| %>
	<% if @post.errors.any?%>
	<div id="errors">	
		<h2><%=pluralize(@post.errors.count,"error")%> preveted this post form saving</h2>
	<ul>
		<%@post.errors.full_messages.each do |msg|%>
			<li><%=msg%></li>
		<%end%>
	</ul>
	</div>
	<%end%>
<p>
	<%=f.label :title%><br/>
	<%=f.text_field :title%>
</p>
<p>
	<%=f.label :body%><br/>
	<%=f.text_area :body%><br/>
</p>
<p>
	<%=f.submit%>
</p>
<%end%>

app/views/post/_form_update.html.erb
<%= form_for @post  do |f| %>
	<% if @post.errors.any?%>
	<div id="errors">	
		<h2><%=pluralize(@post.errors.count,"error")%> preveted this post form saving</h2>
	<ul>
		<%@post.errors.full_messages.each do |msg|%>
			<li><%=msg%></li>
		<%end%>
	</ul>
	</div>
	<%end%>
<p>
	<%=f.label :title%><br/>
	<%=f.text_field :title%>
</p>
<p>
	<%=f.label :body%><br/>
	<%=f.text_area :body%><br/>
</p>
<p>
	<%=f.submit%>
</p>
<%end%>

app/views/post/edit.html.erb
 <div id="page_wrapper">
	<h1>Edit Post</h1>
	<%=render 'form_update'%>
</div>

app/views/post/index.html.erb
<% @posts.each do |post|%>
	<div class="post_wrapper">
		<h2 class="title"><%=link_to post.title, post%></h2>
		<p class="date"><%=post.created_at.strftime("%B %d %Y")%></p>
	</div>
<%end%>

app/views/post/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>
<%= render 'form_create'%> 
</div>

app/views/post/show.html.erb
<div id="post_content">
<h1 class="title"><%= @post.title %></h1>
<p class="date">
Submitted <%= time_ago_in_words(@post.created_at) %> Ago
<% if user_signed_in? %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete',post_path(@post),method: :delete, data: { confirm: 'Are you sure?' } %> 
<% end %>
</p>
<p class="body"><%= @post.body %></p>

<div id="comments">
		 <h2>Comments</h2>
		 <%=render 'comments/comment'%>
<% if user_signed_in? %>

<h2>Add a Comment:</h2>

	<%= form_for([@post, @post.comments.build]) do |f|%>
		
		<p>
			<%=f.label :name%><br/>
			<%=f.text_field :name%>
		</p>
		<p>
			<%=f.label :body%><br/>
			<%=f.text_area :body%></br>
		</p>
		<p>
			<%=f.submit%>
		</p>
	<%end%>

</div>

<% end %>

</div>